### ISSUE TITLE
Day 5 part 1 2021

### ISSUE THREAD

**Issue by gogsbread** [odnoletkov/advent-of-code-jq#1]
:wave: Did you modify the input for day 5? I keep getting `jq: error (at <stdin>:1): Expected value before ',' at line 1, column 2` even for just `inputs`
```
 echo '0,9 -> 5,9
                         8,0 -> 0,8
                         9,4 -> 3,4
                         2,2 -> 2,1
                         7,0 -> 7,4
                         6,4 -> 2,0
                         0,9 -> 2,9
                         3,4 -> 1,4
                         0,0 -> 8,8
                         5,5 -> 8,2' | jq -n '[inputs]'

```

**Comment by odnoletkov** [comment]
Hey, you are missing the `-R` flag – it makes jq interpret input as strings. Without the flag jq expects valid JSON input, and `0,9 -> 5,9` is obv. not a valid JSON.

I just realized example invocation in README used wrong file (lowercase `-r`) – fixed that, thanks

**Comment by gogsbread** [comment]
Btw, this repo is awesome. Didn't even realize that jq is a Turing complete interpreter.
